### ISSUE TITLE
Dynamic routes in Enact

### ISSUE THREAD

**Issue by nghiatv** [enactjs/samples#63]
Hi,
I am working with Enact for building a webOS app. But i have a problem with dynamic route in Enact.
When i use `react-router`, when i define route as above: 
```
<Route  path="/livechannel/:id" component={LiveChannel} />
```
i got this warning when routing to` localhost:8000/livechannel/2` : 
```
Uncaught SyntaxError: Unexpected token <
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:8080/livechannel/main.css".
```

and i found a note in your docs :
**However, if you want to use another UI library like material-ui, reactstrap, or react-router, just use npm install.**

Can you provide some sample about dynamic routes or intergrate with `react-router`?

Thanks.

**Comment by webOS101** [comment]
Hello!  We use `react-router` ourselves in some projects and have not experienced any issues.  That said, the error message seems to indicate there's a bad character in your CSS file.  Is it possible you have an error in an included CSS/LESS file?  Are there any warnings when serving your app?  If you have a minimal reproduction case, please share that.  Also, please let us know which version of Enact and the CLI you are using.

**Comment by ericblade** [comment]
fwiw, I also use react-router, and have no problems.  I haven't attempted to use the : notation, though, I'm pretty much a noob to react-router, and am using it very minimally.

**Comment by nghiatv** [comment]
@webOS101  here is my repo.
[Lg-enact](https://github.com/nghiatv/lg-webos/blob/master/src/App/App.js)
I am using `react-router` in App/App.js.
if i edit to:
`<Route  path="/category/:id" component={Category} />`
 i got error `Uncaught SyntaxError: Unexpected token <`.
then i remove it, nothing error
 Please take a look and tell me how to fix it. Many thank.

**Comment by nghiatv** [comment]
@ericblade  i'm new in `react-router`. Can you show me your sample code using `react-router`?

**Comment by ericblade** [comment]
I have a couple of custom router components that wrap in a check for a couple of different authorizations, but it basically just looks like

````
<Route path="/path/" component={ComponentName}>
````

Nothing special about it.  Sorry I'm not much help there.

**Comment by sugardave** [comment]
The problem is that webpack is substituting the location of where that path's sources (html, js, css) are.  In this case it's trying to load from `host:/livechannel` instead of `host:/`.  You can work around this with a custom HTML template that adds `<base href="/">` to the `<head>` of the document.

You can copy the one from https://github.com/enactjs/cli/blob/master/config/html-template.ejs into the root of your project and add it.

Then you need to modify the `package.json`:
```
...
"enact": {
  "template": "html-template.ejs",
  "theme": "moonstone"
}
...
```
Once you restart the server it should work as you expect.

We may need to think about updating the cli to provide this by default.

**Comment by nghiatv** [comment]
@sugardave thank you so much. It works perfectly.

**Comment by ericblade** [comment]
Ah, yeah, I was using /path not /path/ .. when i put a / after the route path, and tried to access it, i could no longer get at any of the source, so sort of same problem, manifesting differently.  Thanks @sugardave
